[package]
name = "rlse"
version = "0.1.0"
edition = "2021"

[lib]
name = "rlse"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neon = "1"
toml = "0.8.8"
serde = { version = "1.0", features = ["derive"] }
